/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tankoyunu1;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Yusuf
 */
public class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaEkran2
     */
    static OyunAlani OA;
    public AnaEkran() {
        initComponents();
        CenterScreen();
        OA=null;
    }
     
  public void CenterScreen()
    {
        Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        player1_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        player2_name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        player1_tank1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        player1_tank2 = new javax.swing.JRadioButton();
        player1_tank3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        player1_tank4 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        player2_tank4 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        player2_tank3 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        player2_tank2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        player2_tank1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_uyari2 = new javax.swing.JLabel();
        lbl_uyari1 = new javax.swing.JLabel();
        cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\tank-main.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 520, 450));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("O");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("WAR");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLAYER 1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 163, -1, -1));

        player1_name.setBackground(new java.awt.Color(36, 47, 65));
        player1_name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        player1_name.setForeground(new java.awt.Color(255, 255, 255));
        player1_name.setToolTipText("");
        player1_name.setBorder(null);
        jPanel2.add(player1_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 360, 43));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLAYER 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        player2_name.setBackground(new java.awt.Color(36, 47, 65));
        player2_name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        player2_name.setForeground(new java.awt.Color(255, 255, 255));
        player2_name.setToolTipText("");
        player2_name.setBorder(null);
        jPanel2.add(player2_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 364, 43));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 364, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 10));

        player1_tank1.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(player1_tank1);
        player1_tank1.setSelected(true);
        player1_tank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1_tank1ActionPerformed(evt);
            }
        });
        jPanel2.add(player1_tank1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\red-tank-up.png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\blue-tank-up.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        player1_tank2.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(player1_tank2);
        player1_tank2.setEnabled(false);
        player1_tank2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1_tank2ActionPerformed(evt);
            }
        });
        jPanel2.add(player1_tank2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        player1_tank3.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(player1_tank3);
        player1_tank3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1_tank3ActionPerformed(evt);
            }
        });
        jPanel2.add(player1_tank3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\black-tank-up.png")); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\green-tank-up.png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        player1_tank4.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(player1_tank4);
        player1_tank4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1_tank4ActionPerformed(evt);
            }
        });
        jPanel2.add(player1_tank4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\red-tank-up.png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jRadioButton5.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\red-tank-up.png")); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\red-tank-up.png")); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jRadioButton7.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\red-tank-up.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jRadioButton8.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\green-tank-up.png")); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        player2_tank4.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup2.add(player2_tank4);
        player2_tank4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2_tank4ActionPerformed(evt);
            }
        });
        jPanel2.add(player2_tank4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\black-tank-up.png")); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        player2_tank3.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup2.add(player2_tank3);
        player2_tank3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2_tank3ActionPerformed(evt);
            }
        });
        jPanel2.add(player2_tank3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\blue-tank-up.png")); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        player2_tank2.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup2.add(player2_tank2);
        player2_tank2.setSelected(true);
        player2_tank2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2_tank2ActionPerformed(evt);
            }
        });
        jPanel2.add(player2_tank2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\3.SINIF DERSLERİ\\Java\\TankOyunu1\\images\\red-tank-up.png")); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        player2_tank1.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup2.add(player2_tank1);
        player2_tank1.setEnabled(false);
        player2_tank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2_tank1ActionPerformed(evt);
            }
        });
        jPanel2.add(player2_tank1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BAŞLA");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 180, 50));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("F");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TANKS");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 365, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 150, 10));

        lbl_uyari2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_uyari2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbl_uyari2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        lbl_uyari1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_uyari1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbl_uyari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        cikis.setBackground(new java.awt.Color(36, 47, 65));
        cikis.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cikis.setForeground(new java.awt.Color(255, 255, 255));
        cikis.setText("ÇIKIŞ");
        cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikisMouseClicked(evt);
            }
        });
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        jPanel2.add(cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 180, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 480, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        player1_tank1.setActionCommand("red");
        player1_tank2.setActionCommand("blue");
        player1_tank3.setActionCommand("black");
        player1_tank4.setActionCommand("green");
        player2_tank1.setActionCommand("red");
        player2_tank2.setActionCommand("blue");
        player2_tank3.setActionCommand("black");
        player2_tank4.setActionCommand("green");
        boolean kontrol1=true; 
        boolean kontrol2=true;
        if(player1_name.getText().length()<1 || player1_name.getText().length()>8)
        {
            lbl_uyari1.setText("player1 ismi 8 karakterden büyük ya da boş olmamalıdır. !");
            kontrol1=false;
        }
        else
        {
            lbl_uyari1.setText("");
            kontrol1=true;
        }
            
        if(player2_name.getText().length()<1 || player2_name.getText().length()>8)
        {
            lbl_uyari2.setText("player2 ismi 8 karakterden büyük ya da boş olmamalıdır. !");
            kontrol2=false;
        }
         else
        {
            lbl_uyari2.setText("");
            kontrol2=true;
        }
        if(kontrol1==true && kontrol2==true)
        {
            OA=null;
            String tank1Renk=buttonGroup1.getSelection().getActionCommand().toString();
            String tank2Renk=buttonGroup2.getSelection().getActionCommand().toString();
            OA=new OyunAlani(player1_name.getText(),tank1Renk,player2_name.getText(),tank2Renk);
            OA.show();
            this.dispose();
        }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public static void OyunAlaniDisabled()
    {
        OA.enable(false);
    }
    private void player1_tank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1_tank1ActionPerformed
        if(player1_tank1.isSelected()==true)
        {
            player2_tank1.setEnabled(false);
            player2_tank2.setEnabled(true);
            player2_tank3.setEnabled(true);
            player2_tank4.setEnabled(true);
        }
    }//GEN-LAST:event_player1_tank1ActionPerformed

    private void player1_tank2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1_tank2ActionPerformed
        if(player1_tank2.isSelected()==true)
        {
            player2_tank2.setEnabled(false);
            player2_tank1.setEnabled(true);
            player2_tank3.setEnabled(true);
            player2_tank4.setEnabled(true);
        }
    }//GEN-LAST:event_player1_tank2ActionPerformed

    private void player1_tank3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1_tank3ActionPerformed
         if(player1_tank3.isSelected()==true)
        {
            player2_tank3.setEnabled(false);
            player2_tank1.setEnabled(true);
            player2_tank2.setEnabled(true);
            player2_tank4.setEnabled(true);
        }
    }//GEN-LAST:event_player1_tank3ActionPerformed

    private void player1_tank4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1_tank4ActionPerformed
         if(player1_tank4.isSelected()==true)
        {
            player2_tank4.setEnabled(false);
            player2_tank1.setEnabled(true);
            player2_tank3.setEnabled(true);
            player2_tank2.setEnabled(true);
        }
    }//GEN-LAST:event_player1_tank4ActionPerformed

    private void player2_tank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2_tank1ActionPerformed
          if(player2_tank1.isSelected()==true)
        {
            player1_tank1.setEnabled(false);
            player1_tank2.setEnabled(true);
            player1_tank3.setEnabled(true);
            player1_tank4.setEnabled(true);
        }
    }//GEN-LAST:event_player2_tank1ActionPerformed

    private void player2_tank2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2_tank2ActionPerformed
          if(player2_tank2.isSelected()==true)
        {
            player1_tank2.setEnabled(false);
            player1_tank1.setEnabled(true);
            player1_tank3.setEnabled(true);
            player1_tank4.setEnabled(true);
        }
    }//GEN-LAST:event_player2_tank2ActionPerformed

    private void player2_tank3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2_tank3ActionPerformed
          if(player2_tank3.isSelected()==true)
        {
            player1_tank3.setEnabled(false);
            player1_tank1.setEnabled(true);
            player1_tank2.setEnabled(true);
            player1_tank4.setEnabled(true);
        }
    }//GEN-LAST:event_player2_tank3ActionPerformed

    private void player2_tank4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2_tank4ActionPerformed
         if(player2_tank4.isSelected()==true)
        {
            player1_tank4.setEnabled(false);
            player1_tank1.setEnabled(true);
            player1_tank2.setEnabled(true);
            player1_tank3.setEnabled(true);
        }
    }//GEN-LAST:event_player2_tank4ActionPerformed

    private void cikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cikisMouseClicked

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cikis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbl_uyari1;
    private javax.swing.JLabel lbl_uyari2;
    private javax.swing.JTextField player1_name;
    private javax.swing.JRadioButton player1_tank1;
    private javax.swing.JRadioButton player1_tank2;
    private javax.swing.JRadioButton player1_tank3;
    private javax.swing.JRadioButton player1_tank4;
    private javax.swing.JTextField player2_name;
    private javax.swing.JRadioButton player2_tank1;
    private javax.swing.JRadioButton player2_tank2;
    private javax.swing.JRadioButton player2_tank3;
    private javax.swing.JRadioButton player2_tank4;
    // End of variables declaration//GEN-END:variables
}
